- menu_name: "Services"

- name: "Impressum"
  url: "/impressum/"
  title: "Impressum"

- name: "RSS"
  url: "/feed.xml"
  title: "RSS Feed Abonnieren"

- name: "Atom"
  url: "/atom.xml"
  title: "Atom Feed Abonnieren"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap f&uml;r Google Webmaster Tools"
