- menu_name: "Services"

- name: "Kontakt"
  url: "/contact/"
  title: "Kontakt"

- name: "RSS"
  url: "/feed.xml"
  title: "RSS Feed Abonnieren"

- name: "Atom"
  url: "/atom.xml"
  title: "Atom Feed Abonnieren"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap f&uml;r Google Webmaster Tools"
